# Generated by Django 4.2.7 on 2023-11-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voos',
            fields=[
                ('id', models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('airline', models.CharField(default='', max_length=3)),
                ('flight', models.IntegerField(default=0, max_length=5)),
                ('airpot_from', models.CharField(default='', max_length=3)),
                ('airpot_to', models.CharField(default='', max_length=3)),
                ('day_of_week', models.CharField(default=0, max_length=1)),
                ('time', models.IntegerField(default=0)),
                ('delay', models.IntegerField(default=0)),
            ],
        ),
    ]
